# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: send_audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10send_audio.proto\x12\raudio_service\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\" \n\rAudioResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rServerRequest\x12\x0f\n\x07mycheck\x18\x01 \x01(\t\"\"\n\x0eServerResponse\x12\x10\n\x08isonline\x18\x01 \x01(\x08\x32V\n\x0c\x41udioService\x12\x46\n\tSendAudio\x12\x19.audio_service.AudioChunk\x1a\x1c.audio_service.AudioResponse(\x01\x32\\\n\x0cServerStatus\x12L\n\x0b\x43heckStatus\x12\x1c.audio_service.ServerRequest\x1a\x1d.audio_service.ServerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'send_audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=35
  _globals['_AUDIOCHUNK']._serialized_end=61
  _globals['_AUDIORESPONSE']._serialized_start=63
  _globals['_AUDIORESPONSE']._serialized_end=95
  _globals['_SERVERREQUEST']._serialized_start=97
  _globals['_SERVERREQUEST']._serialized_end=129
  _globals['_SERVERRESPONSE']._serialized_start=131
  _globals['_SERVERRESPONSE']._serialized_end=165
  _globals['_AUDIOSERVICE']._serialized_start=167
  _globals['_AUDIOSERVICE']._serialized_end=253
  _globals['_SERVERSTATUS']._serialized_start=255
  _globals['_SERVERSTATUS']._serialized_end=347
# @@protoc_insertion_point(module_scope)
